apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: p67ya5cz3-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c9fc6ba9d0.ajj5.p3.openshiftapps.com/rhtap/rhtap-qe:94d4b1dcfb12be5d52560a9a737e795ba935f114@sha256:cd9c4427b2510c0a2b19bb52aea5cdc19c168a1ac4e6f3813182db3468a96200
          name: container-image
